// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs17GRTGSuGAGaLoqIEgdbngyW-dsmPUI',
    appId: '1:1004692756958:web:0ce62c8c4431d87020254f',
    messagingSenderId: '1004692756958',
    projectId: 'olxapp-e2887',
    authDomain: 'olxapp-e2887.firebaseapp.com',
    storageBucket: 'olxapp-e2887.appspot.com',
    measurementId: 'G-CQQ73RMJKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUY_SSwiuWrZK98DamQZCjwWMGuYZbKE',
    appId: '1:1004692756958:android:637c35c5d50ad0ae20254f',
    messagingSenderId: '1004692756958',
    projectId: 'olxapp-e2887',
    storageBucket: 'olxapp-e2887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgLT3sZg1MmzsWKFA_xYzwQa3-tcMwUK4',
    appId: '1:1004692756958:ios:d210a253b61f2f2f20254f',
    messagingSenderId: '1004692756958',
    projectId: 'olxapp-e2887',
    storageBucket: 'olxapp-e2887.appspot.com',
    iosClientId: '1004692756958-6j70mt4u3s1akafj9rqbequqobcba4h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.olx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgLT3sZg1MmzsWKFA_xYzwQa3-tcMwUK4',
    appId: '1:1004692756958:ios:d210a253b61f2f2f20254f',
    messagingSenderId: '1004692756958',
    projectId: 'olxapp-e2887',
    storageBucket: 'olxapp-e2887.appspot.com',
    iosClientId: '1004692756958-6j70mt4u3s1akafj9rqbequqobcba4h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.olx',
  );
}
